### ISSUE TITLE
access error

### ISSUE THREAD

**Issue by finneyb** [tmoertel/tempest-personal-weather#1]
Thank you for this project, exactly what I was looking for.  Unfortunately, I am not getting past the first couple of phases of the data retrieval.   Running the program against my station and token (shown here as yyy and xxx), I get 

pkg/tempest/download-data/tempest-personal-weather> python3.11 ./sync_weather.py --api_token xxx --database ./home_weather.db --device_id yyy --v
INFO:root:syncing data for device yyy
INFO:root:device 99686 has most_recent_timestamp = 0
INFO:root:fetching data for device yyy: timestamp range (1691467742, 1691554142)
Traceback (most recent call last):
  File "/home/brad/pkg/tempest/download-data/tempest-personal-weather/./sync_weather.py", line 297, in <module>
    main()
  File "/home/brad/pkg/tempest/download-data/tempest-personal-weather/./sync_weather.py", line 293, in main
    _sync_device(args.api_token, device_id, con)
  File "/home/brad/pkg/tempest/download-data/tempest-personal-weather/./sync_weather.py", line 205, in _sync_device
    _sync_device_for_range(api_token, device_id, con, start_timestamp, end_timestamp)
  File "/home/brad/pkg/tempest/download-data/tempest-personal-weather/./sync_weather.py", line 222, in _sync_device_for_range
    data_rows = _fetch_device_data_for_range(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brad/pkg/tempest/download-data/tempest-personal-weather/./sync_weather.py", line 268, in _fetch_device_data_for_range
    response = urllib.request.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

I verified that  can snag the data with the station id and token using the REST method directly  as in

https://swd.weatherflow.com/swd/rest/observations/station/yyy?token=xxx

so I believe I have not messed up the token value or station id in the Python script.  I have also verified that the database exists and the columns have been created.

Any ideas?  Thanks.

**Comment by finneyb** [comment]
User error!  I didn't (and still don't completely) understand the difference between the station id (or the location id) and device id.  In some places, the station id is listed as the device id.  Anyway, I know have the sensor package device id and the script works perfectly.
